name: diff
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
      issues: write
    name: Test diff
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Diff PR test coverage vs default branch
        id: testCoverageDiff
        if: ${{ github.event_name == 'pull_request' }}
        uses: anuraag016/Jest-Coverage-Diff@V1.4
        with:
          fullCoverageDiff: false
          afterSwitchCommand: "npm ci"
          delta: 0.1
